# Generated by Django 4.2.7 on 2026-04-17 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easypaisa_number', models.CharField(default='03XX-XXXXXXX', max_length=20)),
                ('easypaisa_account_name', models.CharField(default='Velaur Fragrances', max_length=100)),
                ('jazzcash_number', models.CharField(default='03XX-XXXXXXX', max_length=20)),
                ('jazzcash_account_name', models.CharField(default='Velaur Fragrances', max_length=100)),
                ('welcome_message', models.TextField(default='🌹 Welcome to Velaur! I am Vera, your luxury fragrance assistant. How can I help you today?')),
                ('bot_name', models.CharField(default='Vera', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chatbot Configuration',
                'verbose_name_plural': 'Chatbot Configuration',
            },
        ),
        migrations.CreateModel(
            name='CustomReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_phrase', models.CharField(help_text='When user says this phrase, use custom reply', max_length=200)),
                ('reply', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Custom Reply',
                'verbose_name_plural': 'Custom Replies',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('keywords', models.CharField(blank=True, help_text='Comma separated keywords e.g: delivery,shipping,time', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='StorePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('delivery', 'Delivery Policy'), ('refund', 'Refund Policy'), ('exchange', 'Exchange Policy'), ('payment', 'Payment Policy'), ('general', 'General Policy')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Store Policy',
                'verbose_name_plural': 'Store Policies',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('jwt_token', models.TextField(blank=True)),
                ('cart_data', models.JSONField(default=dict)),
                ('checkout_step', models.CharField(default='idle', max_length=50)),
                ('pending_order_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
