# Generated by Django 4.2.7 on 2026-04-16 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('easypaisa', 'EasyPaisa'), ('jazzcash', 'JazzCash')], max_length=20)),
                ('transaction_number', models.CharField(help_text='Transaction ID from EasyPaisa/JazzCash', max_length=100)),
                ('sender_number', models.CharField(help_text='Mobile number used for payment', max_length=20)),
                ('screenshot', models.ImageField(upload_to='payment_screenshots/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
        ),
    ]
